import { Source, Layer, type LayerProps } from 'react-map-gl/maplibre';
import { useMapStore } from '../../stores/map.store';
import { useEffect, useState } from 'react';

const unclusteredLayer: LayerProps = {
  id: 'vessels-unclustered',
  type: 'symbol',
  source: 'vessels',
  'source-layer': 'vessels', // CRITICAL: Matches the layer name generated by ST_AsMVT in Postgres
  layout: {
    'icon-image': 'vessel-arrow',
    'icon-size': [
      'interpolate', ['linear'], ['zoom'],
      2, 0.35, 6, 0.45, 10, 0.55, 15, 0.7,
    ],
    'icon-rotate': [
      'case',
      ['>', ['coalesce', ['get', 'course'], 0], 0], ['get', 'course'],
      ['coalesce', ['get', 'heading'], 0]
    ],
    'icon-rotation-alignment': 'map',
    'icon-allow-overlap': true,
    'icon-ignore-placement': true,
  },
  paint: {
    'icon-color': [
      'match',
      ['get', 'vessel_type'], 
      'Cargo', '#2E7D32',   
      'Tanker', '#C62828',   
      'Passenger', '#1565C0',   
      'Fishing', '#6A1B9A',   
      'Special/Tug', '#E65100',
      'High Speed Craft', '#00838F',
      '#455A64' // Default
    ],
    'icon-halo-color': '#FFFFFF',
    'icon-halo-width': 1.5,
  },
};

export function VesselLayer() {
  const { showVessels } = useMapStore((s) => s.layers);
  const [tick, setTick] = useState(0);

  // Auto-refresh the Vector Tiles every 5 seconds to simulate real-time radar sweep
  useEffect(() => {
    const interval = setInterval(() => {
      setTick(t => t + 1);
    }, 5000);
    return () => clearInterval(interval);
  }, []);

  const TILE_URL = `${import.meta.env.VITE_SUPABASE_URL}rest/v1/rpc/vessel_tiles?z={z}&x={x}&y={y}&apikey=${import.meta.env.VITE_SUPABASE_ANON_KEY}&tick=${tick}`;

  return (
    <Source
      id="vessels"
      type="vector"
      tiles={[TILE_URL]}
      minzoom={2}
      maxzoom={14}
    >
      {showVessels && <Layer {...(unclusteredLayer as any)} />}
    </Source>
  );
}